import '../../(with navigation)/globals.css'
import AuthProvider from '@/app/components/AuthProvider'

import { Roboto } from 'next/font/google' 

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})
 
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <AuthProvider>
        <body className={roboto.className}>{children}</body>
      </AuthProvider>
    
    </html>
  )
}
